name: PRnew
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]    
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: get version
      - id: set_var
        run: |
          content=`cat ${{ github.workspace }}/config.json`          
          echo "::set-output name=packageJson::$content"
      - name:  Echo output   
        run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).project_name}}" 
      
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT1 }}
          repository: joemon-david/UITestAutomationSample
          event-type: my-event
          client-payload: '{"prnumber": "${{ github.event.number }}", "checkrunid": "${{ github.run_id }}"}'
