name: User Input Workflow

on:
  workflow_dispatch:
    inputs:
      messaging_module:
        description: 'Messaging_Module'
        required: true
        type: boolean
        default: false

jobs:
  user_input_job:
    runs-on: ubuntu-latest

    steps:
      - name: Convert boolean input to numeric value
        id: convert
        run: |
          if [ "${{ github.event.inputs.messaging_module }}" = "true" ]; then
            echo  "{enable_messaging}={1}" >> $GITHUB_OUTPUT
          else
            echo  "{enable_messaging}={0}" >> $GITHUB_OUTPUT
          fi

      - name: Print numeric value
        run: |
          echo "Numeric value: ${{ steps.convert.outputs.enable_messaging }}"
