name: GitHub Secrets to Env Variables

on: push

jobs:
  DEV_ENG_PRF:
    environment: DEV_ENG_PRF
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python      
      env:
        ENV_SECRET: ${{ secrets.BASE_URL }} 
        REPO_SECRET: ${{ secrets.TENANT_ID }}
        PLAIN_TEXT: joemon.david
      run: python -c 'import os;print(os.environ)'
    
    - name: Test inline env vars for python
      run: ENV_SECRET=${{ secrets.TENANT_ID }}  python -c 'import os;print(os.environ)'
